import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen overflow-hidden text-white bg-black">
        <NavBar />
        <main className="ml-72 h-screen overflow-y-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
